# Copyright Vespa.ai. All rights reserved.
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vespa. Big data. Real time. Open source.
description: >- # this means to ignore newlines until "baseurl:"
  Vespa - the open big data serving platform
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.vespa.ai" # the base hostname & protocol for your site, e.g. http://example.com
# Remove this before publishing on github.com
repository: vespa/documentation
repository_url: "https://github.com/vespa-engine/documentation"
google_tag_manager: "GTM-WM6MPVZP"

# Build settings
sass:
  sass_dir: _sass
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

# Keep markdown files in output
keep_files:
  - "*.html.md"

# Exclude from processing.
# The following items will not be processed by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea
  - open_index.json
  - _work/
  - test/
  - "*.pem"
  - "*.yaml"
  - "*.py"
  - llms.txt

search:
  namespace: "open"
  doc_type: "doc"
  do_feed  : true
  do_index_removal_before_feed: false
  feed_endpoints:
    # This config needs to be the same in all files starting with "_" in:
    # vespa-engine/documentation, vespa-engine/pyvespa, vespa-engine/sample-apps,
    # vespaai/blog and vespaai/cloud-site
    #
    # vespacloud-docsearch | prod.aws-us-east-1c
    - url: https://b671e1db.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - open_index.json
    # vespacloud-docsearch | prod.aws-eu-west-1a
    - url: https://ed053d52.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - open_index.json
    # vespacloud-docsearch | prod.gcp-us-central1-f
    - url: https://a341952a.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - open_index.json
    # vespacloud-docsearch | prod.gcp-us-central1-a
    - url: https://ba97230a.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - open_index.json
    # vespacloud-docsearch.cloud-enclave | prod.aws-us-east-1c
    - url: https://cd560c23.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - open_index.json
    # vespacloud-docsearch.cloud-enclave | prod.aws-eu-west-1a
    - url: https://b24dd625.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - open_index.json
    # vespacloud-docsearch.cloud-enclave | prod.gcp-us-central1-f
    - url: https://ab1f72fd.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - open_index.json

defaults:
  -
    scope:
      path  : ""
    values:
      layout: "default"
      index : true

variables:
  vespa_version: "8.584.45"
