# Copyright Vespa.ai. All rights reserved.
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vespa. Big data. Real time. Open source.
description: >- # this means to ignore newlines until "baseurl:"
  Vespa - the open big data serving platform
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.vespa.ai" # the base hostname & protocol for your site, e.g. http://example.com
# Remove this before publishing on github.com
repository: vespa/documentation

# Build settings
sass:
  sass_dir: _sass
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea
  - open_index.json
  - _work/
  - test/
  - "*.pem"
  - "*.yaml"
  - "*.py"

search:
  namespace: "open"
  doc_type: "doc"
  do_feed  : true
  do_index_removal_before_feed: false
  feed_endpoints:
    # vespacloud-docsearch // aws // us-east-1c
    - url: https://b671e1db.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - open_index.json
    # vespacloud-docsearch // gcp // us-central1-f
    - url: https://a341952a.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - open_index.json
    # vespacloud-docsearch // aws // eu-west-1a
    - url: https://ed053d52.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - open_index.json
    # vespacloud-docsearch // aws (enclave) // us-west-1c
    - url: https://c967e4f5.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - open_index.json
    # vespacloud-docsearch // gcp (enclave) // us-central1-f
    - url: https://d13733c3.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - open_index.json

defaults:
  -
    scope:
      path  : ""
    values:
      layout: "default"
      index : true

variables:
  vespa_version: "8.500.20"
