shared:
  settings:
    email:
      addresses: [kraune@yahooinc.com]
      statuses: [SUCCESS, FAILURE]
  environment:
    USER_SHELL_BIN: bash
  annotations:
    install-deps-new: &install-deps-new
      install-deps-new: |
        dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
        dnf -y install docker-ce protobuf-compiler protobuf-devel --nobest
        python3 -m pip install --upgrade pip
        python3 -m pip install -qqq -r test/requirements.txt --user
        python3 -m pip install -qqq pytest nbmake --user
        VESPA_CLI_VERSION=$(curl -fsSL https://api.github.com/repos/vespa-engine/vespa/releases/latest | grep -Po '"tag_name": "v\K.*?(?=")') && \
          curl -fsSL https://github.com/vespa-engine/vespa/releases/download/v${VESPA_CLI_VERSION}/vespa-cli_${VESPA_CLI_VERSION}_linux_amd64.tar.gz | tar -zxf - -C /opt && \
          ln -sf /opt/vespa-cli_${VESPA_CLI_VERSION}_linux_amd64/bin/vespa /usr/local/bin/

jobs:
  link-checker-documentation:
    requires: [~pr, ~commit]
    image: ruby:2.6
    annotations:
      screwdriver.cd/buildPeriodically: H H(0-5) * * 1-5 # some time between 12:00 AM UTC (midnight) to 5:59 AM UTC Mon-Fri
    steps:
      - install-bundler: |
          gem install bundler
      - check-links: |
          export LANG=C.UTF-8
          bundle install
          bundle exec jekyll build
          find _site/en _site/documentation -name \*.html | \
            xargs grep -l "Click here if you are not redirected." | xargs rm
          bundle exec htmlproofer \
            --assume-extension .html \
            --enforce_https false \
            --allow-missing-href true \
            --ignore-files '/playground/index.html/' \
            --ignore-urls '/localhost:8080/,/docs.vespa.ai/playground/,/javadoc.io.*#/,/readthedocs.io.*#/' \
            --typhoeus '{"connecttimeout": 10, "timeout": 30, "accept_encoding": "zstd,br,gzip,deflate"}' \
            --hydra '{"max_concurrency": 1}' \
            _site

  verify-guides:
    requires: [~pr, ~commit]
    image: vespaengine/vespa-build-centos-stream8:latest
    annotations:
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: HIGH
      screwdriver.cd/dockerRam: HIGH
      screwdriver.cd/buildPeriodically: H H(0-5) * * 1-5 # some time between 12:00 AM UTC (midnight) to 5:59 AM UTC Mon-Fri
    steps:
      - *install-deps-new
      - run-tests: |
          cd $SD_DIND_SHARE_PATH
          $SD_SOURCE_DIR/test/test.py -c $SD_SOURCE_DIR/test/_test_config.yml -w $SD_SOURCE_DIR

  verify-guides-large:
    requires: [~pr, ~commit]
    sourcePaths: ["en/tutorials/"]
    image: vespaengine/vespa-build-centos-stream8:latest
    annotations:
      screwdriver.cd/cpu: TURBO
      screwdriver.cd/ram: TURBO
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: TURBO
      screwdriver.cd/dockerRam: TURBO
      screwdriver.cd/timeout: 180
      screwdriver.cd/buildPeriodically: H H(0-5) * * 1-5 # some time between 12:00 AM UTC (midnight) to 5:59 AM UTC Mon-Fri
    steps:
      - *install-deps-new
      - run-tests: |
          cd $SD_DIND_SHARE_PATH
          $SD_SOURCE_DIR/test/test.py -c $SD_SOURCE_DIR/test/_test_config-large.yml -w $SD_SOURCE_DIR

  update-vespa-version:
    requires: [~pr]
    sourcePaths: ["screwdriver.yaml"]
    image: buildpack-deps
    annotations:
      screwdriver.cd/buildPeriodically: H H(0-5) * * 1 # some time between 12:00 AM UTC (midnight) to 5:59 AM UTC Mon
    steps:
      - update-to-latest: |
          VESPA_VERSION=$(curl -s 'https://repo1.maven.org/maven2/com/yahoo/vespa/parent/maven-metadata.xml' | \
            grep '<latest>' | sed 's/<\/*latest>//g; s/ //g;')
          echo "Vespa-version is: " ${VESPA_VERSION}
          pwd
          ls -la
          cat _config.yml | sed "s/vespa_version: \"[0-9\.]*\"/vespa_version: \"${VESPA_VERSION}\"/" > _config.yml.new
          mv _config.yml.new _config.yml
          git status --porcelain | wc -l
          changes=$(git status --porcelain | wc -l)
          if (( changes > 0 )); then
            echo "Updating Vespa-version to ${VESPA_VERSION}"
            echo git commit -a -m "Update Vespa-version to ${VESPA_VERSION}"
            echo git pull --rebase
            echo git push
          fi
