shared:
  settings:
    email:
      addresses: [kraune@yahooinc.com]
      statuses: [SUCCESS, FAILURE]
  environment:
    USER_SHELL_BIN: bash
  annotations:
    install-deps: &install-deps
      install-deps: |
        apt update
        apt install -y docker.io zstd maven zip unzip python3-pip net-tools bundler
        python3 -m pip install -qqq -r test/requirements.txt --user
        VESPA_CLI_VERSION=$(curl -fsSL https://api.github.com/repos/vespa-engine/vespa/releases/latest | grep -Po '"tag_name": "v\K.*?(?=")')
        echo "VESPA_CLI_VERSION=$VESPA_CLI_VERSION"
        echo ls -la /usr/local/bin/
        ls -la /usr/local/bin/
        curl -fsSL https://github.com/vespa-engine/vespa/releases/download/v${VESPA_CLI_VERSION}/vespa-cli_${VESPA_CLI_VERSION}_linux_amd64.tar.gz | tar -zxf - -C /opt && \
          ln -sf /opt/vespa-cli_${VESPA_CLI_VERSION}_linux_amd64/bin/vespa /usr/local/bin/
        echo ls -la /usr/local/bin/
        ls -la /usr/local/bin/
        which vespa

jobs:
  link-checker-documentation:
    requires: [~pr, ~commit]
    image: ruby:2.6
    annotations:
      screwdriver.cd/buildPeriodically: H H(0-5) * * 1-5 # some time between 12:00 AM UTC (midnight) to 5:59 AM UTC Mon-Fri
    steps:
      - install-bundler: |
          gem install bundler
      - check-links: |
          export LANG=C.UTF-8
          bundle install
          bundle exec jekyll build
          find _site/en _site/documentation -name \*.html | \
            xargs grep -l "Click here if you are not redirected." | xargs rm
          bundle exec htmlproofer \
            --assume-extension \
            --check-html \
            --file-ignore '/playground/index.html/' \
            --typhoeus '{"connecttimeout": 10, "timeout": 30}' \
            --hydra '{"max_concurrency": 1}' \
            _site

  verify-guides:
    requires: [~pr, ~commit]
    image: buildpack-deps
    annotations:
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: HIGH
      screwdriver.cd/dockerRam: HIGH
      screwdriver.cd/buildPeriodically: H H(0-5) * * 1-5 # some time between 12:00 AM UTC (midnight) to 5:59 AM UTC Mon-Fri
    steps:
      - *install-deps
      - run-tests: |
          cd $SD_DIND_SHARE_PATH
          $SD_SOURCE_DIR/test/test.py -c $SD_SOURCE_DIR/test/_test_config.yml -w $SD_SOURCE_DIR

  verify-guides-large:
    requires: [~pr, ~commit]
    sourcePaths: ["en/tutorials/"]
    image: buildpack-deps
    annotations:
      screwdriver.cd/cpu: TURBO
      screwdriver.cd/ram: TURBO
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: TURBO
      screwdriver.cd/dockerRam: TURBO
      screwdriver.cd/timeout: 180
      screwdriver.cd/buildPeriodically: H H(0-5) * * 1-5 # some time between 12:00 AM UTC (midnight) to 5:59 AM UTC Mon-Fri
    steps:
      - *install-deps
      - run-tests: |
          cd $SD_DIND_SHARE_PATH
          $SD_SOURCE_DIR/test/test.py -c $SD_SOURCE_DIR/test/_test_config-large.yml -w $SD_SOURCE_DIR
