shared:
  settings:
    email:
      addresses: [kraune@yahooinc.com]
      statuses: [SUCCESS, FAILURE]
  environment:
    USER_SHELL_BIN: bash
  annotations:
    screwdriver.cd/restrictPR: fork
    install-deps-new: &install-deps-new
      install-deps-new: |
        dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
        dnf -y install docker-ce protobuf-compiler protobuf-devel python3-pip --nobest
        python3 -m pip install --upgrade pip
        python3 -m pip install -qqq -r test/requirements.txt --user
        python3 -m pip install -qqq pytest nbmake --user
        VESPA_CLI_VERSION=$(curl -fsSL https://api.github.com/repos/vespa-engine/vespa/releases/latest | grep -Po '"tag_name": "v\K.*?(?=")') && \
          curl -fsSL https://github.com/vespa-engine/vespa/releases/download/v${VESPA_CLI_VERSION}/vespa-cli_${VESPA_CLI_VERSION}_linux_amd64.tar.gz | tar -zxf - -C /opt && \
          ln -sf /opt/vespa-cli_${VESPA_CLI_VERSION}_linux_amd64/bin/vespa /usr/local/bin/

jobs:
  link-checker-documentation:
    image: ruby:3.1
    annotations:
      screwdriver.cd/buildPeriodically: H H(0-5) * * 1-5 # some time between 12:00 AM UTC (midnight) to 5:59 AM UTC Mon-Fri
    steps:
      - install-bundler: |
          gem update --system 3.3.3
          gem install bundler
      - check-links: |
          export LANG=C.UTF-8
          bundle install
          bundle exec jekyll build
          #
          # Remove the redirect-files before link-check
          find _site/en _site/documentation -name \*.html | \
            xargs grep -l "Click here if you are not redirected." | xargs rm
          #
          # htmlproofer does not check links inside <code>-elements
          find _site -name \*.html | xargs sed -i'' 's/<code>//g; s/<\/code>//g;'
          #
          bundle exec htmlproofer \
            --assume-extension .html \
            --enforce_https false \
            --allow-missing-href true \
            --ignore-files '/playground/index.html/' \
            --ignore-urls '/localhost:8080/,/docs.vespa.ai/playground/,/javadoc.io.*#/,/readthedocs.io.*#/' \
            --typhoeus '{"connecttimeout": 10, "timeout": 30, "accept_encoding": "zstd,br,gzip,deflate"}' \
            --hydra '{"max_concurrency": 1}' \
            _site

  verify-guides:
    requires: [~pr, ~commit]
    image: vespaengine/vespa-build-centos-stream8:latest
    annotations:
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: HIGH
      screwdriver.cd/dockerRam: HIGH
      screwdriver.cd/buildPeriodically: H H(0-5) * * 1-5 # some time between 12:00 AM UTC (midnight) to 5:59 AM UTC Mon-Fri
    steps:
      - *install-deps-new
      - install-bundler: |
          gem install bundler
          export LANG=C.UTF-8
          bundle install
      - build-site: |
          bundle exec jekyll build
      - check-queries: |
          ./test/test_queries.py _site
      - run-tests: |
          cd $SD_DIND_SHARE_PATH
          $SD_SOURCE_DIR/test/test.py -c $SD_SOURCE_DIR/test/_test_config.yml -w $SD_SOURCE_DIR

  verify-guides-large:
    requires: [~pr, ~commit]
    sourcePaths: ["en/tutorials/"]
    image: vespaengine/vespa-build-centos-stream8:latest
    annotations:
      screwdriver.cd/cpu: TURBO
      screwdriver.cd/ram: TURBO
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: TURBO
      screwdriver.cd/dockerRam: TURBO
      screwdriver.cd/timeout: 180
      screwdriver.cd/buildPeriodically: H H(0-5) * * 1-5 # some time between 12:00 AM UTC (midnight) to 5:59 AM UTC Mon-Fri
    steps:
      - *install-deps-new
      - run-tests: |
          cd $SD_DIND_SHARE_PATH
          $SD_SOURCE_DIR/test/test.py -c $SD_SOURCE_DIR/test/_test_config-large.yml -w $SD_SOURCE_DIR

  update-vespa-version:
    image: buildpack-deps
    annotations:
      screwdriver.cd/buildPeriodically: H H(0-5) * * 1 # some time between 12:00 AM UTC (midnight) to 5:59 AM UTC Mon
    secrets:
      - VESPA_DOC_DEPLOY_KEY
    environment:
       GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
    steps:
      - update-to-latest: |
          # must checkout the repo again using ssh for the credentials to work
          cat << EOF > pushtogit.sh
            #!/bin/bash
            ssh-add -D
            set +x
            ssh-add <(echo $VESPA_DOC_DEPLOY_KEY | base64 -d)
            set -x
            git clone git@github.com:vespa-engine/documentation.git documentation && cd documentation
            VESPA_VERSION=\$(curl -sSL https://repo1.maven.org/maven2/com/yahoo/vespa/parent/maven-metadata.xml | \
              grep -oP '<latest>\K([0-9]+\.[0-9]+\.[0-9]+)')
            echo "Latest Vespa version is: " \${VESPA_VERSION}
            sed -i.orig "s/vespa_version: \"[0-9\.]*\"/vespa_version: \"\${VESPA_VERSION}\"/" _config.yml
            git diff
            changes=\$(git status --porcelain | wc -l)            
            if (( changes > 0 )); then
              echo "Updating Vespa version in documentation to \${VESPA_VERSION}"
              git commit -m "Update Vespa-version to \${VESPA_VERSION} MERGEOK" _config.yml
              git pull --rebase
              git push
            fi            
          EOF
          /usr/bin/ssh-agent /bin/bash pushtogit.sh

  generate-metric-reference:
    image: buildpack-deps
    annotations:
      screwdriver.cd/buildPeriodically: H H(0-5) * * 1 # some time between 12:00 AM UTC (midnight) to 5:59 AM UTC Mon
    secrets:
      - VESPA_DOC_DEPLOY_KEY
    environment:
       GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
    steps:
      - update-to-latest: |
          apt-get update && apt-get -y install python3-requests
          # must checkout the repo again using ssh for the credentials to work
          cat << EOF > pushtogit.sh
            #!/bin/bash
            ssh-add -D
            set +x
            ssh-add <(echo $VESPA_DOC_DEPLOY_KEY | base64 -d)
            set -x
            git clone git@github.com:vespa-engine/documentation.git documentation && cd documentation
            python3 metric_reference_generator.py
            git diff
            changes=\$(git status --porcelain | wc -l)
            if (( changes > 0 )); then
              echo "Updating metric reference"
              git commit -m "Update metric reference" en/reference/*-metrics-reference.html
              git pull --rebase
              git push
            fi
          EOF
          /usr/bin/ssh-agent /bin/bash pushtogit.sh
